### ISSUE TITLE
empty setup.py

### ISSUE THREAD

**Issue by staropram** [south-coast-science/scs_host_rpi#129]
A bunch of stuff requires the module scs_host but the repository has an empty setup.py, how is it installed?

**Comment by ppp-one** [comment]
Hey, did you happen to make any progress on this?

**Comment by bruno-beloff** [comment]
There are many possible permutations of the scs repos, so for the time being we are sticking with the manual install which is detailed here:

https://github.com/south-coast-science/scs_dev/wiki/1:-Installation
